### ISSUE TITLE
Weird error on GitHub Actions

### ISSUE THREAD

**Issue by ream88** [elixir-cldr/cldr_collation#16]
I'm currently encountering a very weird error. During running any mix task, for example `mix gettext.extract` I see the following warning popping up multiple times:

```
{:error,
 {:load_failed,
  ~c"Failed to load NIF library /home/runner/work/app/app/_build/test/lib/ex_cldr_collation/priv/ucol: 'libicui18n.so.74: cannot open shared object file: No such file or directory'"}}
```

Then my code (a module which uses a macro do build a list of countries) crashes:

```
== Compilation error in file lib/app/data/countries.ex ==
** (UndefinedFunctionError) function Cldr.Collation.nif_compare/3 is undefined (module Cldr.Collation is not available)
    (ex_cldr_collation 0.7.5) Cldr.Collation.nif_compare("South Georgia", "Grenada", 1)
```

Any idea would could be the problem? It worked for months, and suddenly stopped without any changes to the repo 😞

**Comment by kipcole9** [comment]
Hmmm, that's very surprising - and not fun when things stop working for unclear reasons.

The error is saying that `libicui18n.so.74` can't be found.  Which would normally be installed by `apt-get libicu` or whatever you use.

Some thoughts:

0. Everything is ok in your dev environment? And production?  Only in GitHub actions is this an issue?
1. Has the base image for the runner changed and perhaps no longer includes `libicu` by default? Therefore you'd need to add a step like `apt-get libicu`
2. I wonder if deleting the action cache might help? That's not a sophisticated suggestion I know, but it has solved other problems in the past.

I'll also force a run in GitHub actions on my side and see if that makes anything clearer.

**Comment by kipcole9** [comment]
I added a GitHub action to the repo and ran it without error. The OS image is `ubuntu-latest`. So now I'm even less sure why you're getting a failure.  Out of date action cache is all I can think of at the moment.

**Comment by ream88** [comment]
Thank you for your quick replies. 

1. Yes, both development and production environments are fine. Development is on a Mac, and production is on [fly.io](http://fly.io/).
2. I tried that, but unfortunately, it didn't work. The runner is ubuntu-latest, which is 22.04, and it hasn't changed for a while, as far as I know.
3. I considered that approach but didn't proceed with it. Instead, I added `mix compile --force ex_cldr_collation` before the other mix tasks.

I will test removing the cache now! Thx again!

**Comment by ream88** [comment]
Ok removing the action cache helped, maybe it did not include the `.so` file:

```yaml
- uses: actions/cache/save@v4
  with:
    path: |
      deps
      _build
    key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
```

```yaml
- uses: actions/cache/restore@v4
  with:
    path: |
      deps
      _build
    key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
    restore-keys: |
      ${{ runner.os }}-mix-
```

I will keep the workaround for now, but it definitely worsens the CI time:

![before](https://github.com/user-attachments/assets/6fd9267e-ff5c-4271-8ec8-879a4cbbf77a)
![after](https://github.com/user-attachments/assets/193442bd-6ce9-43c2-a812-7091a8270c9c)

Thx again for your help 😊
